# SPDX-License-Identifier: MIT
# Copyright (c) 2026 libaoahid contributors
if(NOT DEFINED AOAHID_SOURCE_DIR OR NOT DEFINED AOAHID_TEST_BINARY_DIR)
  message(FATAL_ERROR "AOAHID_SOURCE_DIR and AOAHID_TEST_BINARY_DIR are required")
endif()

file(REMOVE_RECURSE "${AOAHID_TEST_BINARY_DIR}")
file(MAKE_DIRECTORY
    "${AOAHID_TEST_BINARY_DIR}/fixture/include/libusb-1.0"
    "${AOAHID_TEST_BINARY_DIR}/fixture/lib")
file(WRITE "${AOAHID_TEST_BINARY_DIR}/fixture/include/libusb-1.0/libusb.h"
    "#define LIBUSB_API_VERSION 0x01000100\n")
file(WRITE "${AOAHID_TEST_BINARY_DIR}/fixture/lib/${AOAHID_LIBRARY_NAME}" "")

set(_AOAHID_CONFIGURE_COMMAND
    "${CMAKE_COMMAND}"
    -S "${AOAHID_SOURCE_DIR}"
    -B "${AOAHID_TEST_BINARY_DIR}/build"
    -G "${AOAHID_GENERATOR}"
    -DAOAHID_USE_FAKE_LIBUSB=OFF
    -DAOAHID_BUILD_SHARED=ON
    -DAOAHID_BUILD_STATIC=OFF
    -DAOAHID_BUILD_TESTS=OFF
    -DAOAHID_BUILD_EXAMPLES=OFF
    -DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=TRUE
    "-DLIBUSB_INCLUDE_DIR=${AOAHID_TEST_BINARY_DIR}/fixture/include/libusb-1.0"
    "-DLIBUSB_LIBRARY=${AOAHID_TEST_BINARY_DIR}/fixture/lib/${AOAHID_LIBRARY_NAME}")
if(DEFINED AOAHID_GENERATOR_PLATFORM AND NOT AOAHID_GENERATOR_PLATFORM STREQUAL "")
  list(APPEND _AOAHID_CONFIGURE_COMMAND -A "${AOAHID_GENERATOR_PLATFORM}")
endif()

execute_process(
    COMMAND ${_AOAHID_CONFIGURE_COMMAND}
    RESULT_VARIABLE _AOAHID_RESULT
    OUTPUT_VARIABLE _AOAHID_STDOUT
    ERROR_VARIABLE _AOAHID_STDERR)
if(_AOAHID_RESULT EQUAL 0)
  message(FATAL_ERROR "configuration accepted an obsolete libusb header")
endif()
set(_AOAHID_OUTPUT "${_AOAHID_STDOUT}\n${_AOAHID_STDERR}")
if(NOT _AOAHID_OUTPUT MATCHES "libusb headers report LIBUSB_API_VERSION older than 0x0100010C")
  message(FATAL_ERROR
      "configuration failed for an unexpected reason:\n${_AOAHID_OUTPUT}")
endif()
